  name: first workflow
  on:
    workflow_dispatch:

  jobs:
    firstjob:
      runs-on: self-hosted
      steps:
        - name: firstJob script
          shell: cmd
          run: echo Hello World! This is the fist Job

    secondjob:
      runs-on: ubuntu-latest
      steps:
        - name: secondJob script
          shell: bash
          run: |
            echo This is the second Job
            echo and this is a multi-line script
            
